### ISSUE TITLE
[PinIcon] Crash when openning a channel that has a pinned message

### ISSUE THREAD

**Issue by jack652** [qwerasd205/BDPlugins#25] opened 2023-10-14 22:26 UTC
the plugin causes my discord client to Crash when openning a channel that has a pinned message

pinicon v0.1.0
Stable 236850 (4025e11) Host 1.0.9019 x86 (38122) Windows 11

**Comment by qwerasd205** [comment] 2023-10-15 01:41
Duplicate of #22

**Closed as completed by qwerasd205** 2023-10-15 01:41 UTC
