### ISSUE TITLE
Too many pin icons 💀

### ISSUE THREAD

**Issue by Soft-Bred** [qwerasd205/BDPlugins#2] opened 2021-08-29 23:12 UTC
When anything happens to a message (reaction, clicking more (three dots) button, clicking the pin icon), another two icons appear. All these icons are removed after the message is unfocused. 

![image](https://user-images.githubusercontent.com/60551230/131268283-ec9c2bdc-6065-4870-8c5e-0dacd607a31a.png)

**Comment by qwerasd205** [comment] 2021-08-30 00:09
Cannot reproduce, likely another plugin is causing this behaviour. What other plugins are you using?

**Comment by Soft-Bred** [comment] 2021-08-30 00:10
Let me try and turn off all my plugins and try again, didn't think about any other plugins interfering, my bad.

**Comment by Soft-Bred** [comment] 2021-08-30 00:37
Huh, after testing out like 60% of my plugins and restarting like 20 times, I found the plugin that breaks It (for some reason, it doesn't make sense)

https://github.com/Puv1s/ColorTooltips

this only shows colours when a hex code is shown, idk how it has anything to do with a pin icon.

**Comment by qwerasd205** [comment] 2021-09-09 18:56
Fixed in version 0.0.3, which you can download from betterdiscord.app whenever the update gets approved (shouldn't be too long, it's a very small code change)

**Closed by qwerasd205** 2021-09-09 18:56 UTC
